dist: trusty
sudo: required
language:
    - cpp
compiler:
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cmake
script:
    # Link gcc-6 and g++-6 to their standard commands
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    # Export CC and CXX to tell cmake which compiler to use
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    # Check versions of gcc, g++ and cmake
    - gcc -v && g++ -v && cmake --version
    # Go into the source root directory
    - cd $TRAVIS_BUILD_DIR
    # Build: Google Test / Google Mock
    - cd ./dep/
    - git clone https://github.com/google/googletest.git
    - cd ./googletest/
    - mkdir build
    - cd ./build/
    - cmake ../ -G"Unix Makefiles"
    - make
    # Build: Shaka Scheme
    - cd ../../../
    - mkdir cmake-build-debug
    - cd ./cmake-build-debug/
    - cmake ../ -G"Unix Makefiles"
    - make
    - ls
    # Copy any required shared libraries over to operating directory
    - cp ./lib/* ./bin/tst/
    - ls ./bin/
    - ls ./bin/tst/
    # Run unit tests
    - for file in ./bin/tst/unit-*; do "$file"; done
    # Run integration tests
    - for file in ./bin/tst/integ-*; do "$file"; done
